# Generated by Django 6.0.4 on 2026-04-29 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_miles_driving', models.FloatField()),
                ('total_off_duty_hrs', models.FloatField()),
                ('total_sleeper_hrs', models.FloatField()),
                ('total_driving_hrs', models.FloatField()),
                ('total_on_duty_hrs', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_address', models.CharField(max_length=500)),
                ('current_lat', models.FloatField()),
                ('current_lng', models.FloatField()),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_address', models.CharField(max_length=500)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('cycle_hours_used', models.FloatField()),
                ('start_datetime', models.DateTimeField()),
                ('home_tz', models.CharField(default='America/New_York', max_length=64)),
                ('total_distance_mi', models.FloatField()),
                ('total_drive_hours', models.FloatField()),
                ('total_trip_hours', models.FloatField()),
                ('end_datetime', models.DateTimeField()),
                ('route_geometry', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trips.dailylog')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('stop_type', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('rest_30min', '30-Min Break'), ('sleeper_10hr', '10-Hr Sleeper'), ('reset_34hr', '34-Hr Restart')], max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('label', models.CharField(max_length=200)),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('miles_at_stop', models.FloatField(default=0.0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('trip', 'date')},
        ),
    ]
